apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: myspace
  labels:
    app: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: test/consumer
        args:
          - imagePullPolicy=Never
        ports:
          - containerPort: 9001
            protocol: TCP
        imagePullPolicy: IfNotPresent
